### ISSUE TITLE
When sending ctrl_c to ffmpeg in hidden window quits but get tkinter error

### ISSUE THREAD

**Issue by maxrottersman** [arvinpan/console_ctrl#2]
First, THANK YOU.  Works like a charm!  But I do get a background Tkinter? error you may be able to help with.  Here is what I have so far, excuse the mess!  "root." is my tkinter object.  If you have the clean solution please don't hesitate ;)

`def runFFmpeg():
   
    if root.runffmpeg == False:
        print('quitting ffmpeg')
        #console_ctrl.send_ctrl_c(root.p.pid)
        root.cc.send_ctrl_c(root.p.pid)
  
    try:
        if root.runffmpeg == True:
            root.runffmpeg = False
            info = subprocess.STARTUPINFO()
            info.dwFlags = subprocess.STARTF_USESHOWWINDOW
            info.wShowWindow = subprocess.SW_HIDE
            root.p=subprocess.Popen(root.ffmpeg_command, startupinfo=info)  #CREATE_NEW_CONSOLE
           
    finally:
        pass`

`quitting ffmpeg
Exception in Tkinter callback
Traceback (most recent call last):
frame=  107 fps= 25 q=-1.0 Lsize=      80kB time=00:00:04.33 bitrate= 151.1kbits/s dup=1 drop=0 speed=0.995x
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
video:78kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.688462%
  File "c:\Max_Software\a_Python_projects\screen_animation_to_transparent_webm\goofy_screen_recorder_v2.py", line 162, in runFFmpeg
    root.cc.send_ctrl_c(root.p.pid)
  File "C:\Users\mediapc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\console_ctrl\__init__.py", line 7, in send_ctrl_c
    subprocess.check_call([sys.executable, '-m', 'console_ctrl', str(pid)])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 347, in call
    return p.wait(timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1490, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
KeyboardInterrupt`

**Comment by arvinpan** [comment]
Hi @maxrottersman , thank you for giving this a try!
I'm able to reproduce the issue with your code, together with a mocked root object:
```
root = SimpleNamespace(**{
    'runffmpeg': True,
    'ffmpeg_command': ['ping', '127.0.0.1', '-t'],
    'cc': console_ctrl,
    })
```

`console_ctrl` was initially designed to work together with `creationflags=subprocess.CREATE_NEW_CONSOLE`. In your case, after adding creationflags to the `subprocess.Popen(...)` line, it seems to work without error.

Any reason you don't want to keep creationflags? I'm not familiar with `startupinfo` thus does not fully get what it's trying to do.

**Comment by maxrottersman** [comment]
Hi, thanks for getting back to me! I'm sorry I don't know enough to be more helpful.  I'm calling the subprocess from a tkinter button which is part of a tkinter object "root" (which goes into an event loop).

When I create "info = subprocess.STARTUPINFO())" object there is no  ".CREATE_NEW_CONSOLE" property.  But if I send subprocess.CREATE_NEW_CONSOLE in the Popen it works too (but gives an error).

That is:  root.p=subprocess.Popen(root.ffmpeg_command, subprocess.CREATE_NEW_CONSOLE)  #CREATE_NEW_CONSOLE
 
 So this isn't a bug in what you've done, probably, but a problem in using it within a tkinter object?   
 
 How might I do it so using consol_ctrl doesn't trip up tkinter?  If I understand correctly.  I've attached full code [goofy_screen_recorder_v2.zip](https://github.com/arvinpan/console_ctrl/files/10254186/goofy_screen_recorder_v2.zip)

**Comment by arvinpan** [comment]
thanks for those details, before I dig deeper into the code, I'd like to confirm will this work for you?
`root.p=subprocess.Popen(root.ffmpeg_command, startupinfo=info, creationflags=subprocess.CREATE_NEW_CONSOLE)`

CREATE_NEW_CONSOLE belongs to creationflags, on my side it seems to work together with startupinfo=info

**Comment by maxrottersman** [comment]
No need to dig!  That FIXES it!  THANKS!!!!
